blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/HM-Isep/projet-industriel-front/discussions
    about: Please ask and answer questions here for general discussions
  - name: Documentation
    url: https://github.com/HM-Isep/projet-industriel-front#readme
    about: Check the README for setup instructions and documentation
